server:
  context-path: /jadson
  port: 8081
spring:
  freemarker:
    template-loader-path: classpath:templates
    suffix: .ftl
mybatis:
  config-location: classpath:config/mybatis.xml
  type-aliases-package: com.jadson.study.domain
  mapper-locations: classpath:mapper/com/jadson/study/*.xml