package com.jadson.study.domain.database;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class SysDictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dic_group
     *
     * @mbggenerated
     */
    private String dicGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dic_name
     *
     * @mbggenerated
     */
    private String dicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dic_value
     *
     * @mbggenerated
     */
    private String dicValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.ordering
     *
     * @mbggenerated
     */
    private Integer ordering;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.state
     *
     * @mbggenerated
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.id
     *
     * @return the value of sys_dictionary.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.id
     *
     * @param id the value for sys_dictionary.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dic_group
     *
     * @return the value of sys_dictionary.dic_group
     *
     * @mbggenerated
     */
    public String getDicGroup() {
        return dicGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dic_group
     *
     * @param dicGroup the value for sys_dictionary.dic_group
     *
     * @mbggenerated
     */
    public void setDicGroup(String dicGroup) {
        this.dicGroup = dicGroup == null ? null : dicGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dic_name
     *
     * @return the value of sys_dictionary.dic_name
     *
     * @mbggenerated
     */
    public String getDicName() {
        return dicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dic_name
     *
     * @param dicName the value for sys_dictionary.dic_name
     *
     * @mbggenerated
     */
    public void setDicName(String dicName) {
        this.dicName = dicName == null ? null : dicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dic_value
     *
     * @return the value of sys_dictionary.dic_value
     *
     * @mbggenerated
     */
    public String getDicValue() {
        return dicValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dic_value
     *
     * @param dicValue the value for sys_dictionary.dic_value
     *
     * @mbggenerated
     */
    public void setDicValue(String dicValue) {
        this.dicValue = dicValue == null ? null : dicValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.remark
     *
     * @return the value of sys_dictionary.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.remark
     *
     * @param remark the value for sys_dictionary.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.ordering
     *
     * @return the value of sys_dictionary.ordering
     *
     * @mbggenerated
     */
    public Integer getOrdering() {
        return ordering;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.ordering
     *
     * @param ordering the value for sys_dictionary.ordering
     *
     * @mbggenerated
     */
    public void setOrdering(Integer ordering) {
        this.ordering = ordering;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.state
     *
     * @return the value of sys_dictionary.state
     *
     * @mbggenerated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.state
     *
     * @param state the value for sys_dictionary.state
     *
     * @mbggenerated
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.type
     *
     * @return the value of sys_dictionary.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.type
     *
     * @param type the value for sys_dictionary.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.parent_id
     *
     * @return the value of sys_dictionary.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.parent_id
     *
     * @param parentId the value for sys_dictionary.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
    }
}